name: Mirror source code

on:
  schedule:
    - cron: '0/5 * * * *'

jobs:
  mirror:
    name: Mirror
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Mirror source files
        run: .github/workflows/update.sh

      - name: Rebase
        run: .github/workflows/rebase.sh
